version: "2.3"
services:
  api:
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config_postgres.json:/app/config.json

  postgres:
    image: postgres:alpine
    container_name: poc_psql
    ports:
      - "5432:5432"
    volumes:
      - ./post_psql.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U" ,"${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: poc_psql_admin
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hi@mris.dev
      - PGADMIN_DEFAULT_PASSWORD=password
